name: Auto deploy artifacts on release

on:
  release:
    types: [published]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: '0'

      - name: Release tag
        run: |
          git describe --tags --always --first-parent
          git tag

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

     FIXME:
      - name: Publish application
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Upload reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2